---
title: "Datathon 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}
library(tidyverse)
library(broom)
library(knitr)
library(dplyr)
library(skimr)
library(regclass)
```

```{r load_data}
library(readr)

training = read_csv("training_tallskinny.csv")
validation = read_csv("validation_tallskinny.csv")
interest_topics = read_csv("interest_topics.csv")
```

```{r omit_na}
training <- na.omit(training)
```

```{r filter}
num <- c("303", "304", "305","306","307","308","309","310","311","312","313","314","315")

ce <- training %>%
  filter(topic_id %in% num)
```

```{r}
training %>%
  ggplot(aes(x = log(ltiFeatures))) +
  geom_histogram() +
  labs(title = "Histogram of log(Level of long-term interest in the topic)")
```

```{r}
dataset1 <- training %>%
  mutate(short_interest_level = case_when(
    is.na(stiFeatures) == FALSE ~ stiFeatures,
    is.na(stiFeatures) == TRUE ~ 0
  )) %>%
  mutate(long_interest_level = case_when(
    is.na(ltiFeatures) == FALSE ~ ltiFeatures,
    is.na(ltiFeatures) == TRUE ~ 0
  ))
```

```{r}
sti_mean <- dataset1 %>% summarise(mean(short_interest_level))
lti_mean <- dataset1 %>% summarise(mean(long_interest_level))
```

```{r}
dataset2 <- dataset1  %>%
  mutate(sti_cat = case_when(
    short_interest_level >= 0.07 ~ "HIGH",
    short_interest_level < 0.07 ~ "LOW"
  )) %>%
  mutate(lti_cat = case_when(
    long_interest_level >= 0.007 ~ "HIGH",
    long_interest_level < 0.007 ~ "LOW"
  ))
```

```{r}
dataset2 %>%
  ggplot(aes(x = inAudience, fill = sti_cat)) + 
  geom_bar(position = "fill")
dataset2 %>%
  ggplot(aes(x = inAudience, fill = lti_cat)) + 
  geom_bar(position = "fill")
```

```{r}
topic <- c("/Computers & Electronics")

fin_topics <- interest_topics %>%
  filter(str_detect(topic_name, "/Finance"))

fin<-training %>%
  filter(topic_id %in% fin_topics$topic_id)

ggplot()+geom_jitter(aes(x= ltiFeatures, y=inAudience), fin)

ggplot()+geom_jitter(aes(x= stiFeatures, y=inAudience), fin)

logistic= glm(inAudience ~ ltiFeatures+stiFeatures, data = fin, family = 'binomial')

summary(logistic)

confusion_matrix(logistic)
```



